"""Add url and image_url

Revision ID: 339fb272a80d
Revises: 85bb83094ff2
Create Date: 2024-05-11 00:39:06.640104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '339fb272a80d'
down_revision: Union[str, None] = '85bb83094ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('url', sa.String(length=1024), nullable=True))
    op.add_column('event', sa.Column('image_url', sa.String(length=1024), nullable=True))
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.add_column('place', sa.Column('url', sa.String(length=1024), nullable=True))
    op.add_column('place', sa.Column('image_url', sa.String(length=1024), nullable=True))
    op.alter_column('place', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('place', 'address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('place', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('place', 'image_url')
    op.drop_column('place', 'url')
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('event', 'image_url')
    op.drop_column('event', 'url')
    # ### end Alembic commands ###
