"""empty message

Revision ID: bb6176672591
Revises: 339fb272a80d
Create Date: 2024-05-11 16:11:15.537634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bb6176672591'
down_revision: Union[str, None] = '339fb272a80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'event_type',
               existing_type=postgresql.ENUM('standup', 'concerts', 'exhibitions', 'theater', 'musicals', 'children', 'show', 'festivals', name='event_type'),
               nullable=False)
    op.alter_column('event', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('event', 'ended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'ended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('event', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('event', 'event_type',
               existing_type=postgresql.ENUM('standup', 'concerts', 'exhibitions', 'theater', 'musicals', 'children', 'show', 'festivals', name='event_type'),
               nullable=True)
    # ### end Alembic commands ###
