@startuml architecture

actor User as user

database Database <<PostgreSQL>> as db

component Backend <<FastAPI Service>> as back

component Frontend <<Nginx + React>> as front

control Timer <<Cron>> as cron

component "Place Parser" <<Aiomisc Service>> as p_parser

component "Image Recognition" <<Aiomisc Yolo Service>> as f_parser

cloud API <<MTS Live>> as mts

queue "New Places Queue" <<RabbitMQ>> as queue

user -> front

front --> back

back --> db

cron --> p_parser

p_parser --> mts
mts --> p_parser

p_parser --> db
p_parser --> queue

f_parser <-- queue
f_parser --> db

back --> queue

f_parser --> mts


@enduml